const CHART_WIDTH = 400;
const CHART_HEIGHT = 300;
const CHART_ANIMATION_DURATION = 2000;
const CHART_ANIMATION_BEGIN = 500;

export { CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION_DURATION, CHART_ANIMATION_BEGIN };