const CHART_WIDTH = 360;
const CHART_HEIGHT = 180;
const CHART_ANIMATION_DURATION = 2000;
const CHART_ANIMATION_BEGIN = 500;

export { CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION_DURATION, CHART_ANIMATION_BEGIN };